version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmqMqtt
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
      - 1883:1883 
      - 15675:15675
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    volumes:
      - rabbitmqdatamqtt:/var/lib/rabbitmq
      
volumes:
  rabbitmqdatamqtt: